### ISSUE TITLE
MD5 hash creation issue

### ISSUE THREAD

**Issue by integricho** [Outernet-Project/librarian-analytics#7]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/tasks/scheduler.py", line 35, in _execute
    fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_analytics/tasks.py", line 18, in send_analytics
    query = {'stream': dumper.to_string(mark_sent=False)}
  File "/usr/lib/python2.7/site-packages/librarian_analytics/helpers.py", line 65, in to_string
    serialized_data = device_id + StatBitStream.to_bytes(self._stats)
  File "/usr/lib/python2.7/site-packages/librarian_analytics/bitstream.py", line 215, in to_bytes
    return instance.serialize()
  File "/usr/lib/python2.7/site-packages/librarian_analytics/bitstream.py", line 204, in serialize
    bitstream = bitstream + self._to_datagram(item)
  File "/usr/lib/python2.7/site-packages/librarian_analytics/bitstream.py", line 196, in _to_datagram
    data[field.name])
  File "/usr/lib/python2.7/site-packages/librarian_analytics/bitstream.py", line 170, in _run_processor
    return processor(value)
  File "/usr/lib/python2.7/site-packages/librarian_analytics/data.py", line 127, in preprocess_path
    return hashlib.md5(value).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 47: ordinal not in range(128)

**Comment by integricho** [comment]
Fixed in 7bfeaaa4e4d4b4c90915a6f826f91aeb5393da84
